/**
 * return different type of error 
 */
export const errorMessage = {
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    SESSION_INVALID: "SESSION_INVALID",
    SERVER_ERROR: "SERVER_ERROR",
    INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
    USER_ALREADY_EXIST: "USER_ALREADY_EXIST",
    NO_CREDENTIAL: "NO_CREDENTIAL"
}